### ISSUE TITLE
关联文件夹BUG

### ISSUE THREAD

**Issue by cangming99** [BookerLiu/GeekDesk#103]
如果关联的文件夹里，部分快捷方式已经失效了，但是没有及时移除，此时关联这个文件夹会导致程序崩溃
![image](https://user-images.githubusercontent.com/85931842/226908108-a051ecfd-8c93-42c1-8ea6-4cb20c195ed9.png)

**Comment by BookerLiu** [comment]
说明一下哪个版本

**Comment by BookerLiu** [comment]
> 如果关联的文件夹里，部分快捷方式已经失效了，但是没有及时移除，此时关联这个文件夹会导致程序崩溃 ![image](https://user-images.githubusercontent.com/85931842/226908108-a051ecfd-8c93-42c1-8ea6-4cb20c195ed9.png)

@cangming99 麻烦说明一下版本

**Comment by cangming99** [comment]
> 

是刚合并的新功能啦，半年前提的建议有人做了挺激动的，迫不及待试了一下，还没发布版本的那个

**Comment by BookerLiu** [comment]
这个功能还在开发阶段,   所以可能会有一些bug,   感谢反馈🎉
