### ISSUE TITLE
图标部分缺失BUG

### ISSUE THREAD

**Issue by cangming99** [BookerLiu/GeekDesk#105]
目前用的是我自己打包的2.5.14版本，在如图所示的这次更新之后，图标就会缺少一部分（不论是手动添加还是关联文件夹），但是使用搜索却能够搜索到
![image](https://user-images.githubusercontent.com/85931842/232178698-a9a8a466-9fb8-4597-a5c0-335efe7b2863.png)
![image](https://user-images.githubusercontent.com/85931842/232178780-87d44245-104b-4114-8318-284602735f80.png)
![image](https://user-images.githubusercontent.com/85931842/232178855-7afb889c-5291-46ee-b53a-0a8234a5a647.png)

**Comment by BookerLiu** [comment]
2.5.14还在开发和测试中, 可能会有一些BUG, 可以关注下后续的commit,  感谢反馈💕
