### ISSUE TITLE
锁屏后一段时间必现图标消失，需重启恢复

### ISSUE THREAD

**Issue by circlelee815** [BookerLiu/GeekDesk#135]
win11 22H2 22621.3296测试发现，当锁屏一段时间后（可能2-3小时以上）必现图标消失，重启后能恢复。如果不锁屏，即使放置12个小时也不会出现图标消失。

**Comment by BookerLiu** [comment]
目前已经基本定位到了这个bug, 由于开启了硬件加速,  系统休眠/锁屏后会导致WPF程序渲染的bug,  估计会在下个版本修复
