### ISSUE TITLE
Everything集成功能无法使用

### ISSUE THREAD

**Issue by Noah2Y** [BookerLiu/GeekDesk#140]
在设置中开启了EveryThing插件支持,但是无法进行搜索.或许是我方法不对,总之无法看见搜索框出现.
![QQ_1721205284828](https://github.com/user-attachments/assets/1e2eee60-f12b-42aa-ac0e-365ea12abf07)

**Comment by ruchid123123** [comment]
动作里面，修改直接使用
![image](https://github.com/user-attachments/assets/c2bce8ff-5a78-4424-9ad1-f3d0a2a4caec)

**Comment by Noah2Y** [comment]
> 动作里面，修改直接使用 ![image](https://private-user-images.githubusercontent.com/35169879/369245525-c2bce8ff-5a78-4424-9ad1-f3d0a2a4caec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTMzMDEsIm5iZiI6MTcyNzcxMzAwMSwicGF0aCI6Ii8zNTE2OTg3OS8zNjkyNDU1MjUtYzJiY2U4ZmYtNWE3OC00NDI0LTlhZDEtZjNkMGEyYTRjYWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE2MTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExY2E4NGIwNjVkODJmZjZiM2ExMzJmZWExMTc1MWNmMzdlM2VjYTYzYzQwNjY2YTM0YzRjMzg0NDQ4ZTUzYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.It73kBE2qZEi1StVWP5qVrRlCsRIp6qUktinnnsmUHY)

是了，感谢
