### ISSUE TITLE
拾色器问题

### ISSUE THREAD

**Issue by 1062406901** [BookerLiu/GeekDesk#62]
拾色器在电脑使用了dpi缩放时，无法选择整个屏幕

我不会改

**Comment by 1062406901** [comment]
大概是这样
![image](https://user-images.githubusercontent.com/41564361/180672903-6ce382aa-7314-4fa6-b76a-6454d77d1b7a.png)
![image](https://user-images.githubusercontent.com/41564361/180672926-0d8fb19e-6072-4e54-b3e3-78b9c05335a3.png)

**Comment by BookerLiu** [comment]
下个版本修复

**Comment by 1062406901** [comment]
我已经帮你改好了😃
