### ISSUE TITLE
能支持实时文件夹吗

### ISSUE THREAD

**Issue by cangming99** [BookerLiu/GeekDesk#92]
买了Rolan3后才知道一年半没更新了，但是挺喜欢它的实时文件夹功能，GeekDesk不知道能否实现。
就是把整个文件夹作为一个分组，文件夹内的内容改变的话，分组内容也跟着变化.
![image](https://user-images.githubusercontent.com/85931842/196718973-a1749afb-8394-4de3-91fc-331b269065cd.png)

**Comment by BookerLiu** [comment]
感谢建议, 后续增加此功能
